# Site
name: "June 의 블로그"
title: "이것저것 정보공유"
description: " "
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://jiyeon98613.github.io"
baseurl: ""
remote_theme: "wowthemesnet/mediumish-theme-jekyll"

# 날짜 문제 해결을 위해 추가
future: true
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  june:
    name: "June"
    display_name: "June"
    avatar: 'assets/images/avatar.png'
    description: "부천시 약국 정보를 IT 기술로 정리하여 공유하는 June입니다."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
